services:
  backend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /data
    environment:
      - DATABASE_URLS=mongodb://root:rootpassword@mongo-db:27017/development?authSource=admin
      - AUTH_KEY=test
      - ADMIN_KEY=secret
    command: ['pnpm', 'run', 'dev']
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongo-db:
    image: mongo:latest
    container_name: quickbaas-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: quickbaas-mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
    depends_on:
      - mongo-db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
