name: Docker upload to registry
on:
  push:
    branches:
      - main

jobs:
  upload-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image
        run: docker build -t tomas752/quickbaas:latest .
      - name: Push Docker image
        run: docker push tomas752/quickbaas:latest
